-- Bestiary seed data from dnd5eapi.co with curated terrains
-- Generated on 2026-05-19T14:35:10.452Z

INSERT INTO bestiary (index, name, type, size, cr, xp, hp, ac, terrains) VALUES
  ('aboleth', 'Aboleth', 'aberration', 'Large', 10, 5900, 135, 17, '{"water"}'),
  ('acolyte', 'Acolyte', 'humanoid', 'Medium', 0.25, 50, 9, 10, '{"unallied_city","plains","forest"}'),
  ('adult-black-dragon', 'Adult Black Dragon', 'dragon', 'Huge', 14, 11500, 195, 19, '{"swamp","forest"}'),
  ('adult-blue-dragon', 'Adult Blue Dragon', 'dragon', 'Huge', 16, 15000, 225, 19, '{"desert"}'),
  ('adult-brass-dragon', 'Adult Brass Dragon', 'dragon', 'Huge', 13, 10000, 172, 18, '{"desert","plains"}'),
  ('adult-bronze-dragon', 'Adult Bronze Dragon', 'dragon', 'Huge', 15, 13000, 212, 19, '{"water","plains"}'),
  ('adult-copper-dragon', 'Adult Copper Dragon', 'dragon', 'Huge', 14, 11500, 184, 18, '{"mountain","desert"}'),
  ('adult-gold-dragon', 'Adult Gold Dragon', 'dragon', 'Huge', 17, 18000, 256, 19, '{"mountain","plains","forest"}'),
  ('adult-green-dragon', 'Adult Green Dragon', 'dragon', 'Huge', 15, 13000, 207, 19, '{"forest"}'),
  ('adult-red-dragon', 'Adult Red Dragon', 'dragon', 'Huge', 17, 18000, 256, 19, '{"mountain"}'),
  ('adult-silver-dragon', 'Adult Silver Dragon', 'dragon', 'Huge', 16, 15000, 243, 19, '{"mountain","snow"}'),
  ('adult-white-dragon', 'Adult White Dragon', 'dragon', 'Huge', 13, 10000, 200, 18, '{"snow","mountain"}'),
  ('air-elemental', 'Air Elemental', 'elemental', 'Large', 5, 1800, 90, 15, '{"mountain","desert","plains"}'),
  ('ancient-black-dragon', 'Ancient Black Dragon', 'dragon', 'Gargantuan', 21, 33000, 367, 22, '{"swamp","forest"}'),
  ('ancient-blue-dragon', 'Ancient Blue Dragon', 'dragon', 'Gargantuan', 23, 50000, 481, 22, '{"desert"}'),
  ('ancient-brass-dragon', 'Ancient Brass Dragon', 'dragon', 'Gargantuan', 20, 25000, 297, 20, '{"desert","plains"}'),
  ('ancient-bronze-dragon', 'Ancient Bronze Dragon', 'dragon', 'Gargantuan', 22, 41000, 444, 22, '{"water","plains"}'),
  ('ancient-copper-dragon', 'Ancient Copper Dragon', 'dragon', 'Gargantuan', 21, 33000, 350, 21, '{"mountain","desert"}'),
  ('ancient-gold-dragon', 'Ancient Gold Dragon', 'dragon', 'Gargantuan', 24, 62000, 546, 22, '{"mountain","plains"}'),
  ('ancient-green-dragon', 'Ancient Green Dragon', 'dragon', 'Gargantuan', 22, 41000, 385, 21, '{"forest"}'),
  ('ancient-red-dragon', 'Ancient Red Dragon', 'dragon', 'Gargantuan', 24, 62000, 546, 22, '{"mountain"}'),
  ('ancient-silver-dragon', 'Ancient Silver Dragon', 'dragon', 'Gargantuan', 23, 50000, 487, 22, '{"mountain","snow"}'),
  ('ancient-white-dragon', 'Ancient White Dragon', 'dragon', 'Gargantuan', 20, 25000, 333, 20, '{"snow","mountain"}'),
  ('androsphinx', 'Androsphinx', 'monstrosity', 'Large', 17, 18000, 199, 17, '{"desert","plains"}'),
  ('animated-armor', 'Animated Armor', 'construct', 'Medium', 1, 200, 33, 18, '{"unallied_city"}'),
  ('ankheg', 'Ankheg', 'monstrosity', 'Large', 2, 450, 39, 14, '{"plains","forest"}'),
  ('ape', 'Ape', 'beast', 'Medium', 0.5, 100, 19, 12, '{"forest"}'),
  ('archmage', 'Archmage', 'humanoid', 'Medium', 12, 8400, 99, 12, '{"unallied_city"}'),
  ('assassin', 'Assassin', 'humanoid', 'Medium', 8, 3900, 78, 15, '{"unallied_city"}'),
  ('awakened-shrub', 'Awakened Shrub', 'plant', 'Small', 0, 10, 10, 9, '{"forest","swamp"}'),
  ('awakened-tree', 'Awakened Tree', 'plant', 'Huge', 2, 450, 59, 13, '{"forest"}'),
  ('axe-beak', 'Axe Beak', 'beast', 'Large', 0.25, 50, 19, 11, '{"plains","desert"}'),
  ('azer', 'Azer', 'elemental', 'Medium', 2, 450, 39, 15, '{"mountain","desert"}'),
  ('baboon', 'Baboon', 'beast', 'Small', 0, 10, 3, 12, '{"forest","plains"}'),
  ('badger', 'Badger', 'beast', 'Tiny', 0, 10, 3, 10, '{"forest","plains"}'),
  ('balor', 'Balor', 'fiend', 'Huge', 19, 22000, 262, 19, '{"mountain","unallied_city"}'),
  ('bandit', 'Bandit', 'humanoid', 'Medium', 0.125, 25, 11, 12, '{"forest","plains","desert","mountain","unallied_city"}'),
  ('bandit-captain', 'Bandit Captain', 'humanoid', 'Medium', 2, 450, 65, 15, '{"forest","plains","desert","mountain","unallied_city"}'),
  ('barbed-devil', 'Barbed Devil', 'fiend', 'Medium', 5, 1800, 110, 15, '{"unallied_city","mountain"}'),
  ('basilisk', 'Basilisk', 'monstrosity', 'Medium', 3, 700, 52, 12, '{"mountain","desert"}'),
  ('bat', 'Bat', 'beast', 'Tiny', 0, 10, 1, 12, '{"forest","mountain","swamp"}'),
  ('bearded-devil', 'Bearded Devil', 'fiend', 'Medium', 3, 700, 52, 13, '{"unallied_city","mountain"}'),
  ('behir', 'Behir', 'monstrosity', 'Huge', 11, 7200, 168, 17, '{"mountain"}'),
  ('berserker', 'Berserker', 'humanoid', 'Medium', 2, 450, 67, 13, '{"plains","forest","mountain","snow"}'),
  ('black-bear', 'Black Bear', 'beast', 'Medium', 0.5, 100, 19, 11, '{"forest"}'),
  ('black-dragon-wyrmling', 'Black Dragon Wyrmling', 'dragon', 'Medium', 2, 450, 33, 17, '{"swamp"}'),
  ('black-pudding', 'Black Pudding', 'ooze', 'Large', 4, 1100, 85, 7, '{"swamp","unallied_city"}'),
  ('blink-dog', 'Blink Dog', 'fey', 'Medium', 0.25, 50, 22, 13, '{"forest","plains"}'),
  ('blood-hawk', 'Blood Hawk', 'beast', 'Small', 0.125, 25, 7, 12, '{"mountain","plains","forest"}'),
  ('blue-dragon-wyrmling', 'Blue Dragon Wyrmling', 'dragon', 'Medium', 3, 700, 52, 17, '{"desert"}'),
  ('boar', 'Boar', 'beast', 'Medium', 0.25, 50, 11, 11, '{"forest","plains"}'),
  ('bone-devil', 'Bone Devil', 'fiend', 'Large', 9, 5000, 142, 19, '{"unallied_city","desert"}'),
  ('brass-dragon-wyrmling', 'Brass Dragon Wyrmling', 'dragon', 'Medium', 1, 100, 16, 16, '{"desert"}'),
  ('bronze-dragon-wyrmling', 'Bronze Dragon Wyrmling', 'dragon', 'Medium', 2, 450, 32, 17, '{"water","plains"}'),
  ('brown-bear', 'Brown Bear', 'beast', 'Large', 1, 200, 34, 11, '{"forest","mountain"}'),
  ('bugbear', 'Bugbear', 'humanoid', 'Medium', 1, 200, 27, 16, '{"forest","mountain"}'),
  ('bulette', 'Bulette', 'monstrosity', 'Large', 5, 1800, 94, 17, '{"plains","desert","mountain"}'),
  ('camel', 'Camel', 'beast', 'Large', 0.125, 25, 15, 9, '{"desert"}'),
  ('cat', 'Cat', 'beast', 'Tiny', 0, 10, 2, 12, '{"unallied_city","plains"}'),
  ('centaur', 'Centaur', 'monstrosity', 'Large', 2, 450, 45, 12, '{"forest","plains"}'),
  ('chain-devil', 'Chain Devil', 'fiend', 'Medium', 8, 3900, 85, 16, '{"unallied_city"}'),
  ('chimera', 'Chimera', 'monstrosity', 'Large', 6, 2300, 114, 14, '{"mountain"}'),
  ('chuul', 'Chuul', 'aberration', 'Large', 4, 1100, 93, 16, '{"water","swamp"}'),
  ('clay-golem', 'Clay Golem', 'construct', 'Large', 9, 5000, 133, 14, '{"unallied_city"}'),
  ('cloaker', 'Cloaker', 'aberration', 'Large', 8, 3900, 78, 14, '{"mountain","unallied_city"}'),
  ('cloud-giant', 'Cloud Giant', 'giant', 'Huge', 9, 5000, 200, 14, '{"mountain"}'),
  ('cockatrice', 'Cockatrice', 'monstrosity', 'Small', 0.5, 100, 27, 11, '{"plains","forest","swamp"}'),
  ('commoner', 'Commoner', 'humanoid', 'Medium', 0, 10, 4, 10, '{"unallied_city","plains"}'),
  ('constrictor-snake', 'Constrictor Snake', 'beast', 'Large', 0.25, 50, 13, 12, '{"forest","swamp"}'),
  ('copper-dragon-wyrmling', 'Copper Dragon Wyrmling', 'dragon', 'Medium', 1, 200, 22, 16, '{"mountain"}'),
  ('couatl', 'Couatl', 'celestial', 'Medium', 4, 1100, 97, 19, '{"forest","plains"}'),
  ('crab', 'Crab', 'beast', 'Tiny', 0, 10, 2, 11, '{"water"}'),
  ('crocodile', 'Crocodile', 'beast', 'Large', 0.5, 100, 19, 12, '{"swamp","water"}'),
  ('cult-fanatic', 'Cult Fanatic', 'humanoid', 'Medium', 2, 450, 22, 13, '{"unallied_city"}'),
  ('cultist', 'Cultist', 'humanoid', 'Medium', 0.125, 25, 9, 12, '{"unallied_city"}'),
  ('darkmantle', 'Darkmantle', 'monstrosity', 'Small', 0.5, 100, 22, 11, '{"mountain"}'),
  ('death-dog', 'Death Dog', 'monstrosity', 'Medium', 1, 200, 39, 12, '{"desert","plains"}'),
  ('deep-gnome-svirfneblin', 'Deep Gnome (Svirfneblin)', 'humanoid', 'Small', 0.5, 50, 16, 15, '{"mountain"}'),
  ('deer', 'Deer', 'beast', 'Medium', 0, 10, 4, 13, '{"forest","plains"}'),
  ('deva', 'Deva', 'celestial', 'Medium', 10, 5900, 136, 17, '{"mountain","plains"}'),
  ('dire-wolf', 'Dire Wolf', 'beast', 'Large', 1, 200, 37, 14, '{"forest","snow","mountain"}'),
  ('djinni', 'Djinni', 'elemental', 'Large', 11, 7200, 161, 17, '{"desert","mountain"}'),
  ('doppelganger', 'Doppelganger', 'monstrosity', 'Medium', 3, 700, 52, 14, '{"unallied_city"}'),
  ('draft-horse', 'Draft Horse', 'beast', 'Large', 0.25, 50, 19, 10, '{"plains","unallied_city"}'),
  ('dragon-turtle', 'Dragon Turtle', 'dragon', 'Gargantuan', 17, 18000, 341, 20, '{"water"}'),
  ('dretch', 'Dretch', 'fiend', 'Small', 0.25, 25, 18, 11, '{"swamp","unallied_city"}'),
  ('drider', 'Drider', 'monstrosity', 'Large', 6, 2300, 123, 19, '{"forest","mountain"}'),
  ('drow', 'Drow', 'humanoid', 'Medium', 0.25, 50, 13, 15, '{"forest","mountain"}'),
  ('druid', 'Druid', 'humanoid', 'Medium', 2, 450, 27, 11, '{"forest","swamp","plains"}'),
  ('dryad', 'Dryad', 'fey', 'Medium', 1, 200, 22, 11, '{"forest"}'),
  ('duergar', 'Duergar', 'humanoid', 'Medium', 1, 200, 26, 16, '{"mountain"}'),
  ('dust-mephit', 'Dust Mephit', 'elemental', 'Small', 0.5, 100, 17, 12, '{"desert"}'),
  ('eagle', 'Eagle', 'beast', 'Small', 0, 10, 3, 12, '{"mountain","plains","forest"}'),
  ('earth-elemental', 'Earth Elemental', 'elemental', 'Large', 5, 1800, 126, 17, '{"mountain","desert"}'),
  ('efreeti', 'Efreeti', 'elemental', 'Large', 11, 7200, 200, 17, '{"desert"}'),
  ('elephant', 'Elephant', 'beast', 'Huge', 4, 1100, 76, 12, '{"plains"}'),
  ('elk', 'Elk', 'beast', 'Large', 0.25, 50, 13, 10, '{"forest","plains"}'),
  ('erinyes', 'Erinyes', 'fiend', 'Medium', 12, 8400, 153, 18, '{"mountain","unallied_city"}'),
  ('ettercap', 'Ettercap', 'monstrosity', 'Medium', 2, 450, 44, 13, '{"forest"}'),
  ('ettin', 'Ettin', 'giant', 'Large', 4, 1100, 85, 12, '{"mountain","forest"}'),
  ('fire-elemental', 'Fire Elemental', 'elemental', 'Large', 5, 1800, 102, 13, '{"desert","mountain"}'),
  ('fire-giant', 'Fire Giant', 'giant', 'Huge', 9, 5000, 162, 18, '{"mountain"}'),
  ('flesh-golem', 'Flesh Golem', 'construct', 'Medium', 5, 1800, 93, 9, '{"unallied_city"}'),
  ('flying-snake', 'Flying Snake', 'beast', 'Tiny', 0.125, 25, 5, 14, '{"forest","desert"}'),
  ('flying-sword', 'Flying Sword', 'construct', 'Small', 0.25, 50, 17, 17, '{"unallied_city"}'),
  ('frog', 'Frog', 'beast', 'Tiny', 0, 0, 1, 11, '{"swamp","forest"}'),
  ('frost-giant', 'Frost Giant', 'giant', 'Huge', 8, 3900, 138, 15, '{"snow","mountain"}'),
  ('gargoyle', 'Gargoyle', 'elemental', 'Medium', 2, 450, 52, 15, '{"mountain","unallied_city"}'),
  ('gelatinous-cube', 'Gelatinous Cube', 'ooze', 'Large', 2, 450, 84, 6, '{"unallied_city","mountain"}'),
  ('ghast', 'Ghast', 'undead', 'Medium', 2, 450, 36, 13, '{"unallied_city","swamp","forest"}'),
  ('ghost', 'Ghost', 'undead', 'Medium', 4, 1100, 45, 11, '{"unallied_city","swamp","forest"}'),
  ('ghoul', 'Ghoul', 'undead', 'Medium', 1, 200, 22, 12, '{"unallied_city","swamp","forest"}'),
  ('giant-ape', 'Giant Ape', 'beast', 'Huge', 7, 2900, 157, 12, '{"forest"}'),
  ('giant-badger', 'Giant Badger', 'beast', 'Medium', 0.25, 50, 13, 10, '{"forest","plains"}'),
  ('giant-bat', 'Giant Bat', 'beast', 'Large', 0.25, 50, 22, 13, '{"forest","mountain"}'),
  ('giant-boar', 'Giant Boar', 'beast', 'Large', 2, 450, 42, 12, '{"forest","plains"}'),
  ('giant-centipede', 'Giant Centipede', 'beast', 'Small', 0.25, 50, 4, 13, '{"forest","swamp","mountain"}'),
  ('giant-constrictor-snake', 'Giant Constrictor Snake', 'beast', 'Huge', 2, 450, 60, 12, '{"forest","swamp"}'),
  ('giant-crab', 'Giant Crab', 'beast', 'Medium', 0.125, 25, 13, 15, '{"water"}'),
  ('giant-crocodile', 'Giant Crocodile', 'beast', 'Huge', 5, 1800, 85, 14, '{"swamp","water"}'),
  ('giant-eagle', 'Giant Eagle', 'beast', 'Large', 1, 200, 26, 13, '{"mountain"}'),
  ('giant-elk', 'Giant Elk', 'beast', 'Huge', 2, 450, 42, 14, '{"forest","plains"}'),
  ('giant-fire-beetle', 'Giant Fire Beetle', 'beast', 'Small', 0, 10, 4, 13, '{"forest","mountain"}'),
  ('giant-frog', 'Giant Frog', 'beast', 'Medium', 0.25, 50, 18, 11, '{"swamp","forest"}'),
  ('giant-goat', 'Giant Goat', 'beast', 'Large', 0.5, 100, 19, 11, '{"mountain"}'),
  ('giant-hyena', 'Giant Hyena', 'beast', 'Large', 1, 200, 45, 12, '{"plains","desert"}'),
  ('giant-lizard', 'Giant Lizard', 'beast', 'Large', 0.25, 50, 19, 12, '{"desert","forest","swamp"}'),
  ('giant-octopus', 'Giant Octopus', 'beast', 'Large', 1, 200, 52, 11, '{"water"}'),
  ('giant-owl', 'Giant Owl', 'beast', 'Large', 0.25, 50, 19, 12, '{"forest","snow"}'),
  ('giant-poisonous-snake', 'Giant Poisonous Snake', 'beast', 'Medium', 0.25, 50, 11, 14, '{"forest","swamp","desert"}'),
  ('giant-rat', 'Giant Rat', 'beast', 'Small', 0.125, 25, 7, 12, '{"unallied_city","forest","swamp"}'),
  ('giant-rat-diseased', 'Giant Rat (Diseased)', 'beast', 'Small', 0.125, 25, 7, 12, '{"unallied_city","swamp"}'),
  ('giant-scorpion', 'Giant Scorpion', 'beast', 'Large', 3, 700, 52, 15, '{"desert"}'),
  ('giant-sea-horse', 'Giant Sea Horse', 'beast', 'Large', 0.5, 100, 16, 13, '{"water"}'),
  ('giant-shark', 'Giant Shark', 'beast', 'Huge', 5, 1800, 126, 13, '{"water"}'),
  ('giant-spider', 'Giant Spider', 'beast', 'Large', 1, 200, 26, 14, '{"forest","mountain"}'),
  ('giant-toad', 'Giant Toad', 'beast', 'Large', 1, 200, 39, 11, '{"swamp","forest"}'),
  ('giant-vulture', 'Giant Vulture', 'beast', 'Large', 1, 200, 22, 10, '{"desert","plains","mountain"}'),
  ('giant-wasp', 'Giant Wasp', 'beast', 'Medium', 0.5, 100, 13, 12, '{"forest","plains"}'),
  ('giant-weasel', 'Giant Weasel', 'beast', 'Medium', 0.125, 25, 9, 13, '{"forest","plains"}'),
  ('giant-wolf-spider', 'Giant Wolf Spider', 'beast', 'Medium', 0.25, 50, 11, 13, '{"forest","mountain"}'),
  ('gibbering-mouther', 'Gibbering Mouther', 'aberration', 'Medium', 2, 450, 67, 9, '{"swamp","mountain"}'),
  ('glabrezu', 'Glabrezu', 'fiend', 'Large', 9, 5000, 157, 17, '{"unallied_city","mountain"}'),
  ('gladiator', 'Gladiator', 'humanoid', 'Medium', 5, 1800, 112, 16, '{"unallied_city"}'),
  ('gnoll', 'Gnoll', 'humanoid', 'Medium', 0.5, 100, 22, 15, '{"plains","forest","desert"}'),
  ('goat', 'Goat', 'beast', 'Medium', 0, 10, 4, 10, '{"mountain","plains"}'),
  ('goblin', 'Goblin', 'humanoid', 'Small', 0.25, 50, 7, 15, '{"forest","mountain","plains"}'),
  ('gold-dragon-wyrmling', 'Gold Dragon Wyrmling', 'dragon', 'Medium', 3, 700, 60, 17, '{"mountain","plains"}'),
  ('gorgon', 'Gorgon', 'monstrosity', 'Large', 5, 1800, 114, 19, '{"plains","mountain"}'),
  ('gray-ooze', 'Gray Ooze', 'ooze', 'Medium', 0.5, 100, 22, 8, '{"swamp","mountain"}'),
  ('green-dragon-wyrmling', 'Green Dragon Wyrmling', 'dragon', 'Medium', 2, 450, 38, 17, '{"forest"}'),
  ('green-hag', 'Green Hag', 'fey', 'Medium', 3, 700, 82, 17, '{"forest","swamp"}'),
  ('grick', 'Grick', 'monstrosity', 'Medium', 2, 450, 27, 14, '{"mountain"}'),
  ('griffon', 'Griffon', 'monstrosity', 'Large', 2, 450, 59, 12, '{"mountain","plains"}'),
  ('grimlock', 'Grimlock', 'humanoid', 'Medium', 0.25, 50, 11, 11, '{"mountain"}'),
  ('guard', 'Guard', 'humanoid', 'Medium', 0.125, 25, 11, 16, '{"unallied_city"}'),
  ('guardian-naga', 'Guardian Naga', 'monstrosity', 'Large', 10, 5900, 127, 18, '{"forest","desert"}'),
  ('gynosphinx', 'Gynosphinx', 'monstrosity', 'Large', 11, 7200, 136, 17, '{"desert"}'),
  ('half-red-dragon-veteran', 'Half-Red Dragon Veteran', 'humanoid', 'Medium', 5, 1800, 65, 18, '{"mountain"}'),
  ('harpy', 'Harpy', 'monstrosity', 'Medium', 1, 200, 38, 11, '{"mountain"}'),
  ('hawk', 'Hawk', 'beast', 'Tiny', 0, 10, 1, 13, '{"forest","plains","mountain"}'),
  ('hell-hound', 'Hell Hound', 'fiend', 'Medium', 3, 700, 45, 15, '{"mountain","desert"}'),
  ('hezrou', 'Hezrou', 'fiend', 'Large', 8, 3900, 136, 16, '{"swamp","unallied_city"}'),
  ('hill-giant', 'Hill Giant', 'giant', 'Huge', 5, 1800, 105, 13, '{"mountain","plains"}'),
  ('hippogriff', 'Hippogriff', 'monstrosity', 'Large', 1, 200, 19, 11, '{"mountain","plains"}'),
  ('hobgoblin', 'Hobgoblin', 'humanoid', 'Medium', 0.5, 100, 11, 18, '{"forest","mountain","plains"}'),
  ('homunculus', 'Homunculus', 'construct', 'Tiny', 0, 10, 5, 13, '{"unallied_city"}'),
  ('horned-devil', 'Horned Devil', 'fiend', 'Large', 11, 7200, 178, 18, '{"mountain","unallied_city"}'),
  ('hunter-shark', 'Hunter Shark', 'beast', 'Large', 2, 450, 45, 12, '{"water"}'),
  ('hydra', 'Hydra', 'monstrosity', 'Huge', 8, 3900, 172, 15, '{"swamp"}'),
  ('hyena', 'Hyena', 'beast', 'Medium', 0, 10, 5, 11, '{"plains","desert"}'),
  ('ice-devil', 'Ice Devil', 'fiend', 'Large', 14, 11500, 180, 18, '{"snow","mountain"}'),
  ('ice-mephit', 'Ice Mephit', 'elemental', 'Small', 0.5, 100, 21, 11, '{"snow","mountain"}'),
  ('imp', 'Imp', 'fiend', 'Tiny', 1, 200, 10, 13, '{"unallied_city"}'),
  ('invisible-stalker', 'Invisible Stalker', 'elemental', 'Medium', 6, 2300, 104, 14, '{"mountain","desert","unallied_city"}'),
  ('iron-golem', 'Iron Golem', 'construct', 'Large', 16, 15000, 210, 20, '{"unallied_city"}'),
  ('jackal', 'Jackal', 'beast', 'Small', 0, 10, 3, 12, '{"desert","plains"}'),
  ('killer-whale', 'Killer Whale', 'beast', 'Huge', 3, 700, 90, 12, '{"water"}'),
  ('knight', 'Knight', 'humanoid', 'Medium', 3, 700, 52, 18, '{"plains","unallied_city"}'),
  ('kobold', 'Kobold', 'humanoid', 'Small', 0.125, 25, 5, 12, '{"mountain","forest"}'),
  ('kraken', 'Kraken', 'monstrosity', 'Gargantuan', 23, 50000, 472, 18, '{"water"}'),
  ('lamia', 'Lamia', 'monstrosity', 'Large', 4, 1100, 97, 13, '{"desert"}'),
  ('lemure', 'Lemure', 'fiend', 'Medium', 0, 10, 13, 7, '{"unallied_city"}'),
  ('lich', 'Lich', 'undead', 'Medium', 21, 33000, 135, 17, '{"unallied_city"}'),
  ('lion', 'Lion', 'beast', 'Large', 1, 200, 26, 12, '{"plains","desert"}'),
  ('lizard', 'Lizard', 'beast', 'Tiny', 0, 10, 2, 10, '{"forest","desert","swamp"}'),
  ('lizardfolk', 'Lizardfolk', 'humanoid', 'Medium', 0.5, 100, 22, 13, '{"swamp"}'),
  ('mage', 'Mage', 'humanoid', 'Medium', 6, 2300, 40, 12, '{"unallied_city"}'),
  ('magma-mephit', 'Magma Mephit', 'elemental', 'Small', 0.5, 100, 22, 11, '{"mountain"}'),
  ('magmin', 'Magmin', 'elemental', 'Small', 0.5, 100, 9, 14, '{"mountain"}'),
  ('mammoth', 'Mammoth', 'beast', 'Huge', 6, 2300, 126, 13, '{"snow","plains"}'),
  ('manticore', 'Manticore', 'monstrosity', 'Large', 3, 700, 68, 14, '{"mountain","desert"}'),
  ('marilith', 'Marilith', 'fiend', 'Large', 16, 15000, 189, 18, '{"unallied_city","mountain"}'),
  ('mastiff', 'Mastiff', 'beast', 'Medium', 0.125, 25, 5, 12, '{"plains","unallied_city"}'),
  ('medusa', 'Medusa', 'monstrosity', 'Medium', 6, 2300, 127, 15, '{"desert","unallied_city"}'),
  ('merfolk', 'Merfolk', 'humanoid', 'Medium', 0.125, 25, 11, 11, '{"water"}'),
  ('merrow', 'Merrow', 'monstrosity', 'Large', 2, 450, 45, 13, '{"water"}'),
  ('mimic', 'Mimic', 'monstrosity', 'Medium', 2, 450, 58, 12, '{"unallied_city","mountain"}'),
  ('minotaur', 'Minotaur', 'monstrosity', 'Large', 3, 700, 76, 14, '{"mountain","unallied_city"}'),
  ('minotaur-skeleton', 'Minotaur Skeleton', 'undead', 'Large', 2, 450, 67, 12, '{"mountain","unallied_city"}'),
  ('mule', 'Mule', 'beast', 'Medium', 0.125, 25, 11, 10, '{"plains","mountain"}'),
  ('mummy', 'Mummy', 'undead', 'Medium', 3, 700, 58, 11, '{"desert"}'),
  ('mummy-lord', 'Mummy Lord', 'undead', 'Medium', 15, 13000, 97, 17, '{"desert"}'),
  ('nalfeshnee', 'Nalfeshnee', 'fiend', 'Large', 13, 10000, 184, 18, '{"mountain","unallied_city"}'),
  ('night-hag', 'Night Hag', 'fiend', 'Medium', 5, 1800, 112, 17, '{"swamp","unallied_city"}'),
  ('nightmare', 'Nightmare', 'fiend', 'Large', 3, 700, 68, 13, '{"plains","desert","mountain"}'),
  ('noble', 'Noble', 'humanoid', 'Medium', 0.125, 25, 9, 15, '{"unallied_city"}'),
  ('ochre-jelly', 'Ochre Jelly', 'ooze', 'Large', 2, 450, 45, 8, '{"swamp","mountain"}'),
  ('octopus', 'Octopus', 'beast', 'Small', 0, 10, 3, 12, '{"water"}'),
  ('ogre', 'Ogre', 'giant', 'Large', 2, 450, 59, 11, '{"mountain","forest","swamp"}'),
  ('ogre-zombie', 'Ogre Zombie', 'undead', 'Large', 2, 450, 85, 8, '{"mountain","forest","swamp"}'),
  ('oni', 'Oni', 'giant', 'Large', 7, 2900, 110, 16, '{"forest","mountain"}'),
  ('orc', 'Orc', 'humanoid', 'Medium', 0.5, 100, 15, 13, '{"mountain","forest","plains"}'),
  ('otyugh', 'Otyugh', 'aberration', 'Large', 5, 1800, 114, 14, '{"swamp","unallied_city"}'),
  ('owl', 'Owl', 'beast', 'Tiny', 0, 10, 1, 11, '{"forest"}'),
  ('owlbear', 'Owlbear', 'monstrosity', 'Large', 3, 700, 59, 13, '{"forest"}'),
  ('panther', 'Panther', 'beast', 'Medium', 0.25, 50, 13, 12, '{"forest","plains"}'),
  ('pegasus', 'Pegasus', 'celestial', 'Large', 2, 450, 59, 12, '{"mountain","plains","forest"}'),
  ('phase-spider', 'Phase Spider', 'monstrosity', 'Large', 3, 700, 32, 13, '{"forest","mountain"}'),
  ('pit-fiend', 'Pit Fiend', 'fiend', 'Large', 20, 25000, 300, 19, '{"mountain","unallied_city"}'),
  ('planetar', 'Planetar', 'celestial', 'Large', 16, 15000, 200, 19, '{"mountain","plains"}'),
  ('plesiosaurus', 'Plesiosaurus', 'beast', 'Large', 2, 450, 68, 13, '{"water"}'),
  ('poisonous-snake', 'Poisonous Snake', 'beast', 'Tiny', 0.125, 25, 2, 13, '{"forest","swamp","desert"}'),
  ('polar-bear', 'Polar Bear', 'beast', 'Large', 2, 450, 42, 12, '{"snow"}'),
  ('pony', 'Pony', 'beast', 'Medium', 0.125, 25, 11, 10, '{"plains"}'),
  ('priest', 'Priest', 'humanoid', 'Medium', 2, 450, 27, 13, '{"unallied_city"}'),
  ('pseudodragon', 'Pseudodragon', 'dragon', 'Tiny', 0.25, 50, 7, 13, '{"forest","unallied_city"}'),
  ('purple-worm', 'Purple Worm', 'monstrosity', 'Gargantuan', 15, 13000, 247, 18, '{"desert","mountain"}'),
  ('quasit', 'Quasit', 'fiend', 'Tiny', 1, 200, 7, 13, '{"unallied_city"}'),
  ('quipper', 'Quipper', 'beast', 'Tiny', 0, 10, 1, 13, '{"water"}'),
  ('rakshasa', 'Rakshasa', 'fiend', 'Medium', 13, 10000, 110, 16, '{"unallied_city"}'),
  ('rat', 'Rat', 'beast', 'Tiny', 0, 10, 1, 10, '{"unallied_city","forest"}'),
  ('raven', 'Raven', 'beast', 'Tiny', 0, 10, 1, 12, '{"forest","plains"}'),
  ('red-dragon-wyrmling', 'Red Dragon Wyrmling', 'dragon', 'Medium', 4, 1100, 75, 17, '{"mountain"}'),
  ('reef-shark', 'Reef Shark', 'beast', 'Medium', 0.5, 100, 22, 12, '{"water"}'),
  ('remorhaz', 'Remorhaz', 'monstrosity', 'Huge', 11, 7200, 195, 17, '{"snow"}'),
  ('rhinoceros', 'Rhinoceros', 'beast', 'Large', 2, 450, 45, 11, '{"plains"}'),
  ('riding-horse', 'Riding Horse', 'beast', 'Large', 0.25, 25, 13, 10, '{"plains"}'),
  ('roc', 'Roc', 'monstrosity', 'Gargantuan', 11, 7200, 248, 15, '{"mountain"}'),
  ('roper', 'Roper', 'monstrosity', 'Large', 5, 1800, 93, 20, '{"mountain"}'),
  ('rug-of-smothering', 'Rug of Smothering', 'construct', 'Large', 2, 450, 33, 12, '{"unallied_city"}'),
  ('rust-monster', 'Rust Monster', 'monstrosity', 'Medium', 0.5, 100, 27, 14, '{"mountain"}'),
  ('saber-toothed-tiger', 'Saber-Toothed Tiger', 'beast', 'Large', 2, 450, 52, 12, '{"snow","forest"}'),
  ('sahuagin', 'Sahuagin', 'humanoid', 'Medium', 0.5, 100, 22, 12, '{"water"}'),
  ('salamander', 'Salamander', 'elemental', 'Large', 5, 1800, 90, 15, '{"mountain","desert"}'),
  ('satyr', 'Satyr', 'fey', 'Medium', 0.5, 100, 31, 14, '{"forest"}'),
  ('scorpion', 'Scorpion', 'beast', 'Tiny', 0, 10, 1, 11, '{"desert"}'),
  ('scout', 'Scout', 'humanoid', 'Medium', 0.5, 100, 16, 13, '{"forest","plains","mountain"}'),
  ('sea-hag', 'Sea Hag', 'fey', 'Medium', 2, 450, 52, 14, '{"water","swamp"}'),
  ('sea-horse', 'Sea Horse', 'beast', 'Tiny', 0, 0, 1, 11, '{"water"}'),
  ('shadow', 'Shadow', 'undead', 'Medium', 0.5, 100, 16, 12, '{"unallied_city","swamp"}'),
  ('shambling-mound', 'Shambling Mound', 'plant', 'Large', 5, 1800, 136, 15, '{"swamp","forest"}'),
  ('shield-guardian', 'Shield Guardian', 'construct', 'Large', 7, 2900, 142, 17, '{"unallied_city"}'),
  ('shrieker', 'Shrieker', 'plant', 'Medium', 0, 10, 13, 5, '{"forest","swamp"}'),
  ('silver-dragon-wyrmling', 'Silver Dragon Wyrmling', 'dragon', 'Medium', 2, 450, 45, 17, '{"mountain","snow"}'),
  ('skeleton', 'Skeleton', 'undead', 'Medium', 0.25, 50, 13, 13, '{"unallied_city","desert","swamp","forest"}'),
  ('solar', 'Solar', 'celestial', 'Large', 21, 33000, 243, 21, '{"mountain","plains"}'),
  ('specter', 'Specter', 'undead', 'Medium', 1, 200, 22, 12, '{"unallied_city","swamp"}'),
  ('spider', 'Spider', 'beast', 'Tiny', 0, 10, 1, 12, '{"forest","mountain"}'),
  ('spirit-naga', 'Spirit Naga', 'monstrosity', 'Large', 8, 3900, 75, 15, '{"swamp","forest"}'),
  ('sprite', 'Sprite', 'fey', 'Tiny', 0.25, 50, 2, 15, '{"forest"}'),
  ('spy', 'Spy', 'humanoid', 'Medium', 1, 200, 27, 12, '{"unallied_city"}'),
  ('steam-mephit', 'Steam Mephit', 'elemental', 'Small', 0.25, 50, 21, 10, '{"swamp","mountain"}'),
  ('stirge', 'Stirge', 'beast', 'Tiny', 0.125, 25, 2, 14, '{"forest","swamp","mountain"}'),
  ('stone-giant', 'Stone Giant', 'giant', 'Huge', 7, 2900, 126, 17, '{"mountain"}'),
  ('stone-golem', 'Stone Golem', 'construct', 'Large', 10, 5900, 178, 17, '{"unallied_city","mountain"}'),
  ('storm-giant', 'Storm Giant', 'giant', 'Huge', 13, 10000, 230, 16, '{"mountain","water"}'),
  ('succubus-incubus', 'Succubus/Incubus', 'fiend', 'Medium', 4, 1100, 66, 15, '{"unallied_city"}'),
  ('swarm-of-bats', 'Swarm of Bats', 'swarm of Tiny beasts', 'Medium', 0.25, 50, 22, 12, '{"forest","mountain"}'),
  ('swarm-of-beetles', 'Swarm of Beetles', 'swarm of Tiny beasts', 'Medium', 0.5, 100, 22, 12, '{"forest","swamp"}'),
  ('swarm-of-centipedes', 'Swarm of Centipedes', 'swarm of Tiny beasts', 'Medium', 0.5, 100, 22, 12, '{"forest","swamp","desert"}'),
  ('swarm-of-insects', 'Swarm of Insects', 'swarm of Tiny beasts', 'Medium', 0.5, 100, 22, 12, '{"forest","swamp","plains"}'),
  ('swarm-of-poisonous-snakes', 'Swarm of Poisonous Snakes', 'swarm of Tiny beasts', 'Medium', 2, 450, 36, 14, '{"forest","swamp","desert"}'),
  ('swarm-of-quippers', 'Swarm of Quippers', 'swarm of Tiny beasts', 'Medium', 1, 200, 28, 13, '{"water"}'),
  ('swarm-of-rats', 'Swarm of Rats', 'swarm of Tiny beasts', 'Medium', 0.25, 50, 24, 10, '{"unallied_city","swamp"}'),
  ('swarm-of-ravens', 'Swarm of Ravens', 'swarm of Tiny beasts', 'Medium', 0.25, 50, 24, 12, '{"forest","plains"}'),
  ('swarm-of-spiders', 'Swarm of Spiders', 'swarm of Tiny beasts', 'Medium', 0.5, 100, 22, 12, '{"forest","mountain"}'),
  ('swarm-of-wasps', 'Swarm of Wasps', 'swarm of Tiny beasts', 'Medium', 0.5, 100, 22, 12, '{"forest","plains"}'),
  ('tarrasque', 'Tarrasque', 'monstrosity', 'Gargantuan', 30, 155000, 676, 25, '{"plains","desert","mountain"}'),
  ('thug', 'Thug', 'humanoid', 'Medium', 0.5, 100, 32, 11, '{"unallied_city"}'),
  ('tiger', 'Tiger', 'beast', 'Large', 1, 200, 37, 12, '{"forest"}'),
  ('treant', 'Treant', 'plant', 'Huge', 9, 5000, 138, 16, '{"forest"}'),
  ('tribal-warrior', 'Tribal Warrior', 'humanoid', 'Medium', 0.125, 25, 11, 12, '{"forest","plains","desert","snow","mountain"}'),
  ('triceratops', 'Triceratops', 'beast', 'Huge', 5, 1800, 95, 13, '{"plains","forest"}'),
  ('troll', 'Troll', 'giant', 'Large', 5, 1800, 84, 15, '{"forest","swamp","mountain"}'),
  ('tyrannosaurus-rex', 'Tyrannosaurus Rex', 'beast', 'Huge', 8, 3900, 136, 13, '{"plains","forest"}'),
  ('unicorn', 'Unicorn', 'celestial', 'Large', 5, 1800, 67, 12, '{"forest"}'),
  ('vampire-bat', 'Vampire, Bat Form', 'undead', 'Medium', 13, 10000, 144, 16, '{"unallied_city","forest"}'),
  ('vampire-mist', 'Vampire, Mist Form', 'undead', 'Medium', 13, 10000, 144, 16, '{"unallied_city","forest"}'),
  ('vampire-spawn', 'Vampire Spawn', 'undead', 'Medium', 5, 1800, 82, 15, '{"unallied_city","forest"}'),
  ('vampire-vampire', 'Vampire, Vampire Form', 'undead', 'Medium', 13, 10000, 144, 16, '{"unallied_city"}'),
  ('veteran', 'Veteran', 'humanoid', 'Medium', 3, 700, 58, 17, '{"plains","unallied_city","forest"}'),
  ('violet-fungus', 'Violet Fungus', 'plant', 'Medium', 0.25, 50, 18, 5, '{"forest","swamp"}'),
  ('vrock', 'Vrock', 'fiend', 'Large', 6, 2300, 104, 15, '{"mountain","unallied_city"}'),
  ('vulture', 'Vulture', 'beast', 'Medium', 0, 10, 5, 10, '{"desert","plains"}'),
  ('warhorse', 'Warhorse', 'beast', 'Large', 0.5, 100, 19, 11, '{"plains"}'),
  ('warhorse-skeleton', 'Warhorse Skeleton', 'undead', 'Large', 0.5, 100, 22, 13, '{"plains","desert"}'),
  ('water-elemental', 'Water Elemental', 'elemental', 'Large', 5, 1800, 114, 14, '{"water","swamp"}'),
  ('weasel', 'Weasel', 'beast', 'Tiny', 0, 10, 1, 13, '{"forest","plains"}'),
  ('werebear-bear', 'Werebear, Bear Form', 'humanoid', 'Medium', 5, 1800, 135, 11, '{"forest","mountain"}'),
  ('werebear-human', 'Werebear, Human Form', 'humanoid', 'Medium', 5, 1800, 135, 10, '{"forest","mountain","unallied_city"}'),
  ('werebear-hybrid', 'Werebear, Hybrid Form', 'humanoid', 'Medium', 5, 1800, 135, 11, '{"forest","mountain"}'),
  ('wereboar-boar', 'Wereboar, Boar Form', 'humanoid', 'Medium', 4, 1100, 78, 11, '{"forest","plains"}'),
  ('wereboar-human', 'Wereboar, Human Form', 'humanoid', 'Medium', 4, 1100, 78, 10, '{"forest","plains","unallied_city"}'),
  ('wereboar-hybrid', 'Wereboar, Hybrid Form', 'humanoid', 'Medium', 4, 1100, 78, 11, '{"forest","plains"}'),
  ('wererat-human', 'Wererat, Human Form', 'humanoid', 'Medium', 2, 450, 33, 12, '{"unallied_city"}'),
  ('wererat-hybrid', 'Wererat, Hybrid Form', 'humanoid', 'Medium', 2, 450, 33, 12, '{"unallied_city"}'),
  ('wererat-rat', 'Wererat, Rat Form', 'humanoid', 'Medium', 2, 450, 33, 12, '{"unallied_city"}'),
  ('weretiger-human', 'Weretiger, Human Form', 'humanoid', 'Medium', 4, 1100, 120, 12, '{"forest","unallied_city"}'),
  ('weretiger-hybrid', 'Weretiger, Hybrid Form', 'humanoid', 'Medium', 4, 1100, 120, 12, '{"forest"}'),
  ('weretiger-tiger', 'Weretiger, Tiger Form', 'humanoid', 'Medium', 4, 1100, 120, 12, '{"forest"}'),
  ('werewolf-human', 'Werewolf, Human Form', 'humanoid', 'Medium', 3, 700, 58, 11, '{"forest","unallied_city"}'),
  ('werewolf-hybrid', 'Werewolf, Hybrid Form', 'humanoid', 'Medium', 3, 700, 58, 12, '{"forest"}'),
  ('werewolf-wolf', 'Werewolf, Wolf Form', 'humanoid', 'Medium', 3, 700, 58, 12, '{"forest"}'),
  ('white-dragon-wyrmling', 'White Dragon Wyrmling', 'dragon', 'Medium', 2, 450, 32, 16, '{"snow"}'),
  ('wight', 'Wight', 'undead', 'Medium', 3, 700, 45, 14, '{"swamp","forest","unallied_city"}'),
  ('will-o-wisp', 'Will-o''-Wisp', 'undead', 'Tiny', 2, 450, 22, 19, '{"swamp","forest"}'),
  ('winter-wolf', 'Winter Wolf', 'monstrosity', 'Large', 3, 700, 75, 13, '{"snow"}'),
  ('wolf', 'Wolf', 'beast', 'Medium', 0.25, 50, 11, 13, '{"forest","plains","snow"}'),
  ('worg', 'Worg', 'monstrosity', 'Large', 0.5, 100, 26, 13, '{"forest","plains"}'),
  ('wraith', 'Wraith', 'undead', 'Medium', 5, 1800, 67, 13, '{"unallied_city","swamp"}'),
  ('wyvern', 'Wyvern', 'dragon', 'Large', 6, 2300, 110, 13, '{"mountain"}'),
  ('xorn', 'Xorn', 'elemental', 'Medium', 5, 1800, 73, 19, '{"mountain"}'),
  ('young-black-dragon', 'Young Black Dragon', 'dragon', 'Large', 7, 2900, 127, 18, '{"swamp","forest"}'),
  ('young-blue-dragon', 'Young Blue Dragon', 'dragon', 'Large', 9, 5000, 152, 18, '{"desert"}'),
  ('young-brass-dragon', 'Young Brass Dragon', 'dragon', 'Large', 6, 2300, 110, 17, '{"desert","plains"}'),
  ('young-bronze-dragon', 'Young Bronze Dragon', 'dragon', 'Large', 8, 3900, 142, 18, '{"water","plains"}'),
  ('young-copper-dragon', 'Young Copper Dragon', 'dragon', 'Large', 7, 2900, 119, 17, '{"mountain"}'),
  ('young-gold-dragon', 'Young Gold Dragon', 'dragon', 'Large', 10, 5900, 178, 18, '{"mountain","plains"}'),
  ('young-green-dragon', 'Young Green Dragon', 'dragon', 'Large', 8, 3900, 136, 18, '{"forest"}'),
  ('young-red-dragon', 'Young Red Dragon', 'dragon', 'Large', 10, 5900, 178, 18, '{"mountain"}'),
  ('young-silver-dragon', 'Young Silver Dragon', 'dragon', 'Large', 9, 5000, 168, 18, '{"mountain","snow"}'),
  ('young-white-dragon', 'Young White Dragon', 'dragon', 'Large', 6, 2300, 133, 17, '{"snow","mountain"}'),
  ('zombie', 'Zombie', 'undead', 'Medium', 0.25, 50, 22, 8, '{"unallied_city","swamp","forest"}')
ON CONFLICT (index) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  size = EXCLUDED.size,
  cr = EXCLUDED.cr,
  xp = EXCLUDED.xp,
  hp = EXCLUDED.hp,
  ac = EXCLUDED.ac,
  terrains = EXCLUDED.terrains;
